### ISSUE TITLE
Unrecognized function or variable 'lsqfitma'

### ISSUE THREAD

**Issue by briochemc** [bbcael/opal#1]
Hi,

I just had a quick skim of the code and tried running it, but it threw an error because I don't have `lsqfitma`:

```matlab
Unrecognized function or variable 'lsqfitma'.
```

Culprit:
https://github.com/bbcael/opal/blob/2f3b02697b1acb36d302381d9d85d17a65892ea7/opal_github_1.m#L33

Is that function from a specific toolbox? Or is it a more private function? Maybe it can be shared here, too? 

Good luck moving forward,
Cheers,
Benoit

**Comment by bbcael** [comment]
Bonjour Benoit,
Sorry, you’re right, I should have included this! It's added now. 
Best,
Cael
